FROM node:20-alpine3.18

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN chown -R node:node /usr/src/app

USER node

EXPOSE 8000


CMD ["npm", "start"]
